config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  post '/create_chat', to: 'chats#create_chat', as: :quick_chat

  resources :users, only: [:show, :edit, :update] do
    member do
      get :followers
      get :following
      get :books
      get :lists
      get :bookclubs
    end
  end

  resources :follows, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :books, only: [:index, :show, :new, :create] do
    post 'mark_as_read', on: :member
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :bookclubs, only: [:new, :create, :edit, :update]
  end

  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  resources :bookclubs, only: [:index, :show, :edit, :update, :destroy] do
    resources :bookclub_users, only: [:create]
    resources :discussions, only: [:create]
  end

  resources :likes, only: [:destroy]
  resources :reviews, only: [] do
    resources :likes, only: [:create]
    resources :comments, only: [:index, :create]
  end


  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :bookmarks, dependent: :destroy
  has_many :books, through: :bookmarks
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :destroy]

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.user = current_user
    if @list.save
      redirect_to dashboard_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/views/lists/new.html.erb
<!-- Title -->
<div class="container mt-3">
  <div class="d-flex align-items-center mb-4 position-relative">
    <%= link_to root_path, class: "btn rounded-pill bg-white position-absolute", style: "color: #751F1F; left: 0;" do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
    <h3 class="text-center mb-0 w-100" style="color: #0C0C0C;">Create a New List</h3>
  </div>
</div>
<div class="container">
  <h3 class="text-center mb-4" style="color: #751F1F;"><%= @book.title %></h3>
  <%= simple_form_for(@list) do |f| %>
    <%= f.error_notification %>
    <%= f.hidden_field :book_id, value: @book.id if params[:book_id] %>
    <div class="mb-3">
      <%= f.label :name, class: "text-center mb-2 d-block", style: "color: #751F1F;" do %>
        <h5>Name of the list</h5>
      <% end %>
      <%= f.text_field :name, class: "form-control d-flex align-items-center bg-white rounded-4 opacity-80 px-3 shadow-sm py-3 w-100 border-0" %>
    </div>
    <%= f.button :submit, class: "btn rounded-4 py-2 w-100 mb-2", style: "color: #fff; background-color: #751F1F;" do %>
      <h5>Create</h5>
    <% end %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="container mt-3">
  <div class="d-flex align-items-center justify-content-center mb-4 position-relative">
    <%= link_to :back, class: "btn rounded-pill bg-white position-absolute", style: "color: #751F1F; left: 0;" do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>
    <h3 class="text-center mb-0 w-100" style="color: #0C0C0C;"><%= @list.name %></h3>
    <%= link_to new_list_bookmark_path(@list), class: "btn rounded-pill", style: "color: #751F1F;" do %>
      <i class="fa-solid fa-plus text-12"></i>
    <% end %>
  </div>
</div>
<div class="container" style="margin-bottom: 96px;">
  <!--<%= link_to "Add a book", new_list_bookmark_path(@list), class: "btn btn-outline-dark rounded-pill px-4", style: "color: #751F1F; border-color: #751F1F;", data: { bs_toggle: "modal", bs_target: "#new_book_modal" } %>-->
  <div class="row">
    <% @list.bookmarks.each do |bookmark| %>
      <% book = bookmark.book %>
      <div class="col-auto">
        <%= link_to book_path(book), class: "text-decoration-none" do %>
          <div class="col-16 d-flex mb-3 align-items-center">
            <%= cl_image_tag book.cover.key, class: "rounded-3 me-3", style:"height: 80px; aspect-ratio: 2 / 3; object-fit: cover; margin-bottom: 1rem; box-shadow: 6px 6px 10px rgba(0, 0, 0, 0.1);", alt: book.title if book.cover.attached? %>
            <div>
              <h5 style="margin-bottom: 4px; color: #751F1F;" class="fw-medium">
                <%= book.title %>
              </h5>
              <p class="" style="margin-bottom: 0;">
                <%= book.author %>
              </p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>
<%= render "bookmarks/modal", list: @list, bookmark: Bookmark.new %>