config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  post '/create_chat', to: 'chats#create_chat', as: :quick_chat

  resources :users, only: [:show, :edit, :update] do
    member do
      get :followers
      get :following
      get :books
      get :lists
      get :bookclubs
    end
  end

  resources :follows, only: [:create, :destroy]
  resources :chats, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  resources :books, only: [:index, :show, :new, :create] do
    post 'mark_as_read', on: :member
    resources :reviews, only: [:new, :create, :edit, :update, :destroy]
    resources :bookclubs, only: [:new, :create, :edit, :update]
  end

  resources :lists, only: [:index, :new, :create, :show, :destroy] do
    resources :bookmarks, only: [:new, :create, :destroy]
  end

  resources :bookclubs, only: [:index, :show, :edit, :update, :destroy] do
    resources :bookclub_users, only: [:create]
    resources :discussions, only: [:create]
  end

  resources :likes, only: [:destroy]
  resources :reviews, only: [] do
    resources :likes, only: [:create]
    resources :comments, only: [:index, :create]
  end


  get "webmanifest"    => "pwa#manifest"
  get "service-worker" => "pwa#service_worker"
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :review, counter_cache: true
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!

  def create
    @review = Review.find(params[:review_id])
    @like = @review.likes.new(user: current_user)

    if @like.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to book_path(@review.book), notice: "Liked!" }
      end
    else
      redirect_to book_path(@review.book), alert: "Unable to like."
    end
  end

  def destroy
    @like = Like.find(params[:id])
    @review = @like.review if @like
    @like.destroy if @like

    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to book_path(@like.review.book), notice: "Unliked!" }
    end
  end
end

app/views/likes/_like_button.html.erb
<% like = current_user.likes.find_by(review: review) %>
<div id="review-<%= review.id %>-likes">
  <% if like %>
    <%= button_to like_path(like),
                  method: :delete,
                  class: "btn p-0 d-flex align-items-center gap-2",
                  style: "border: none;",
                  form: { data: { turbo: true } } do %>
      <i class="fa-solid fa-heart" style="color: #751F1F;"></i>
      <span><%= review.likes_count || 0 %></span>
    <% end %>
  <% else %>
    <%= button_to review_likes_path(review_id: review.id),
                  method: :post,
                  class: "btn p-0 d-flex align-items-center gap-2",
                  style: "border: none;",
                  form: { data: { turbo: true } } do %>
      <i class="fa-regular fa-heart" style="color: #751F1F;"></i>
      <span><%= review.likes_count || 0 %></span>
    <% end %>
  <% end %>
</div>

app/views/likes/create.turbo_stream.erb
<%= turbo_stream.replace "review-#{@review.id}-likes" do %>
  <%= render partial: "likes/like_button", locals:  { review: @review } %>
<% end %>

app/views/likes/destroy.turbo_stream.erb
<%= turbo_stream.replace "review-#{@review.id}-likes" do %>
  <%= render partial: "likes/like_button", locals:  { review: @review } %>
<% end %>